name: Update CV Metrics and Generate PDF

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-cv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install missing dependencies
        run: pip install ads

      - name: Run update script to fetch metrics
        env:
          ADS_API_KEY: ${{ secrets.ADS_API_KEY }}
        run: python update_metrics.py

      # - name: Update CV with new metrics
      #   run: python update_cv.py  # Updates cv.tex with latest citation data

      - name: Install LaTeX (with XeLaTeX support)
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-latex-extra texlive-pictures
#          sudo apt-get install -y texlive-full

      - name: Create Private Info File
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PHONE: ${{ secrets.PHONE }}
        run: |
            echo '\newcommand{\myPhone}{'"$PHONE"'}' > sections/private_info.tex
            echo '\newcommand{\myEmail}{'"$EMAIL"'}' >> sections/private_info.tex

      - name: Compile LaTeX CV
        run: |
          xelatex cv.tex
          bibtex cv || true  # Run only if bibliography is present
          xelatex cv.tex
          xelatex cv.tex  # Run again for proper cross-referencing
          rm -f *.aux *.log *.out *.bbl *.blg *.toc *.lof *.lot  # Cleanup temp files

      - name: Upload CV PDF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CV
          path: cv.pdf

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add cv.pdf
          git commit -m "Updated CV metrics and regenerated CV PDF" || exit 0
          git push
